"""empty message

Revision ID: 98148b9710e6
Revises: bf1e54f26db5
Create Date: 2023-10-04 13:30:22.048819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98148b9710e6'
down_revision = 'bf1e54f26db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_order_amt')

    op.drop_table('order')
    with op.batch_alter_table('orderdetails', schema=None) as batch_op:
        batch_op.drop_index('ix_orderdetails_details_amt')
        batch_op.drop_index('ix_orderdetails_details_qty')

    op.drop_table('orderdetails')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('payment_ibfk_2', type_='foreignkey')
        batch_op.drop_column('payment_order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('payment_ibfk_2', 'order', ['payment_order_id'], ['order_id'])

    op.create_table('orderdetails',
    sa.Column('details_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('details_qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('details_amt', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('details_order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('details_upload_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['details_order_id'], ['order.order_id'], name='orderdetails_ibfk_1'),
    sa.ForeignKeyConstraint(['details_upload_id'], ['userupload.upload_id'], name='orderdetails_ibfk_2'),
    sa.PrimaryKeyConstraint('details_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('orderdetails', schema=None) as batch_op:
        batch_op.create_index('ix_orderdetails_details_qty', ['details_qty'], unique=False)
        batch_op.create_index('ix_orderdetails_details_amt', ['details_amt'], unique=False)

    op.create_table('order',
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('order_amt', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order_date', mysql.DATETIME(), nullable=True),
    sa.Column('order_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_user_id'], ['user.user_id'], name='order_ibfk_1'),
    sa.PrimaryKeyConstraint('order_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index('ix_order_order_amt', ['order_amt'], unique=False)

    # ### end Alembic commands ###
